[package]

name = "ostrov"
description = "R6RS Scheme implementation"
homepage = "https://github.com/razielgn/ostrov"
repository = "https://github.com/razielgn/ostrov"
readme = "README.md"
version = "0.0.1"
keywords = ["language", "lisp", "scheme"]
license = "MIT"
authors = ["Federico Ravasio <ravasio.federico@gmail.com>"]
